### ISSUE TITLE
A Couple Things...

### ISSUE THREAD

**Issue by benjaminaplin** [benjaminaplin/benjaminaplin.github.io#3]
Hey Fritz: I have a few things that I could use your help with:
1.  I am having some trouble with the '.this' within objects. I am getting an error saying that a player  method  'is not a function' when I use '. this'.
2. Again having an issue with scope, where i can get the value of player.arrayPlayerHand only in some parts of the program. I have tried moving the function calls and have tested it in the browse console, but haven't figured it out yet..

Thanks!
Ben

**Comment by andrewfritz86** [comment]
OK. Let's meet in a bit.
